const politicalSearchTerms: { [key: string]: any } = {
  0: [
    "greta thunberg is good for america",
    "alexandria ocasio cortez being awsome",
    "pro democrat biden",
    "biden's good climate change policy",
    "green new deal biden",
    "biden vs trump's climate change policy",
    "biden will lead renewable energy",
    "how biden will stop florida climate change",
    "why biden's climate change plan will work",
    "biden is handling coronavirus better than trump",
    "demecrat's listen to health care advice",
    "obamacare biden will work",
    "biden will improve health care",
    "demecrats are better than the republicans in a pandemic",
    "what is biden's coronavirus plan",
    "biden will improve the job market",
    "democrats will lower florida unemployment",
    "biden paid leave announcements",
    "biden build back better america",
    "george floyd biden",
    "biden is better for younger americans",
    "biden restore the soul of america",
    "biden unite for a better america",
    "biden our best days still lie ahead",
    "trump should be impeached",
    "trump should be in jail",
    "biden is pro women",
    "biden rally near me",
  ],
  1: [],
  2: [
    "military spending trump",
    "military trump",
    "trump iran",
    "coronavirus trump",
    "trump handling of coronavirus",
    "trump coronavirus china",
    "obamagate",
    "make america great again",
    "maga",
    "deep state",
    "climate change policy",
    "renewable energy biden",
    "florida climate change",
    "climate change biden",
    "coronavirus biden",
    "coronavirus tests",
  ],

  3: [],
  4: [
    "trump should reopen the economy",
    "trump patriotic education is good",
    "trump is the best negotiator",
    "trump won't let other nations walk over america",
    "there should be tariffs on china",
    "america won the trade war trump",
    "no gun reform",
    "trump should arrest immigrants for use",
    "trump should ban immigration",
    "trump was right to close borders",
    "trump to stop illegal immegration to make america great",
    "stop caravan immegration",
    "trump is better than sleep biden",
    "trump will stop terrorism",
    "trump will sto muslim terrorism",
    "war on terror trump",
    "trump should double miltary spending to keep the terrorists out",
    "trump is the best for the military",
    "trump was right about iran",
    "trump is immune to coronavirus ",
    "coronavirus is just the flue fox news",
    "fox news says it how it is",
    "obamagate is real",
    "make america great again",
    "maga all the way",
    "deep state is real",
    "how to keep America great",
    "joe biden is radical left",
    "trump is the hero of christians",
    "trump reduce unemployment",
    "hillary is crooked",
    "no one else can do it better than trump",
    "its all china's fault",
    "trump is the best",
    "biden is corrupt",
    "the radical left",
    "trump rally near me",
  ],
};

export default politicalSearchTerms;
